config/routes.rb
Moysky::Application.routes.draw do

  resources :weibos do
    resources :comments
  end

  get "home/index"

  root :to => 'home#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :commenterid, :ctime,:weibo_id
  default_scope order 'ctime desc'
  validates :body,:ctime,:presence => true
  #belongs_to :weibo
  belongs_to :comment,:polymorphic => true
  #belongs_to :parent,:class_name => 'Comment'
  #has_many :children,:class_name => 'Comment',:foreign_key => 'parent_id',:dependent => :destroy
  has_many :comments
end

app/models/weibo.rb
class Weibo < ActiveRecord::Base
  attr_accessible :content, :ctime, :flag, :wtype, :userid
  validates :content,:presence => true
  has_many :comments 
  default_scope order 'ctime desc'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    @weibo = Weibo.find(params[:weibo_id])
    if params[:comment_id]==nil
      @comment = @weibo.comments.build(params[:comment])
    else
      @comment = Comment.find(params[:comment_id]).comments.build(params[:comment])
      @comment.update_attributes :weibo_id => params[:weibo_id]
    end
    # @comment = @weibo.comments.build(params[:comment])
    @comment.update_attributes :ctime => Time.now+8*60*60 #,:weibo_id => params[:weibo_id]
    # redirect_to weibos_path
    respond_to do |format|
      format.html { redirect_to weibos_path }
      format.json {render  @comment }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/weibos_controller.rb
# -*- coding: utf-8 -*-
class WeibosController < ApplicationController
  # GET /weibos
  # GET /weibos.json
  def index
    @weibos = Weibo.all
    #build a new msg
    @weibo = Weibo.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @weibos }
    end
  end

  # GET /weibos/1
  # GET /weibos/1.json
  def show
    @weibo = Weibo.find(params[:id])

    respond_to do |format|
     format.html # show.html.erb
      format.json { render json: @weibo }
    end
  end

  # GET /weibos/new
  # GET /weibos/new.json
  def new
    @weibo = Weibo.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @weibo }
    end
  end

  # GET /weibos/1/edit
  def edit
    @weibo = Weibo.find(params[:id])
  end

  # POST /weibos
  # POST /weibos.json
  def create
    @weibo = Weibo.new(params[:weibo])
    @weibo.userid="test"
    # 获取当前时间（本地),纠正了时区
    @weibo.ctime= Time.now+8*60*60
    @weibo.wtype="1"
    @weibo.flag="0"
    respond_to do |format|
      if @weibo.save
        format.html { render @weibo }
        # format.html { redirect_to weibos_path, notice: 'Weibo was successfully created.' }
        format.js{ render @weibo}
        # format.json { head :no_content }
        format.json { render @weibo, status: :created, location: @weibo }
      else
        format.html { render action: "new" }
        format.json { render json: @weibo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /weibos/1
  # PUT /weibos/1.json
  def update
    @weibo = Weibo.find(params[:id])

    respond_to do |format|
      if @weibo.update_attributes(params[:weibo])
        format.html { redirect_to @weibo, notice: 'Weibo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @weibo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weibos/1
  # DELETE /weibos/1.json
  def destroy
    @weibo = Weibo.find(params[:id])
    @weibo.destroy

    respond_to do |format|
      format.html { redirect_to weibos_url }
      format.json { head :no_content }
      # format.js
      format.js { render text:"fff", status: :destroyed }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/weibos_helper.rb
module WeibosHelper
end

app/views/home/index.html.erb
欢迎来到微博天空

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Moysky</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <a class="brand" href="#">马赛克的天空</a>
      <ul class="nav">
        <li><%= link_to '首页',weibos_path %></li>
        <li><a href="#">广场</a></li>
        <li><a href="#">投票</a></li>
      </ul>
    </div>
    </div>
    
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span2">
          ad
          <!--Sidebar content-->
        </div>
        <div class="span8">
          <%= yield %>
        </div>
        <div class="span2">
          customer infosdfasdfasdfasd
        </div>
    </div>
    </div>
</body>
</html>

app/views/weibos/_form.html.erb
<div style="margin-top:7%">
<h4>说说身边的事情吧</h4>
</div>
<%= form_for(@weibo) do |f| %>
  <% if @weibo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@weibo.errors.count, "error") %> prohibited this weibo from being saved:</h2>

      <ul>
      <% @weibo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.text_area :content,:cols=>"40",:rows=>'4',:style =>'width:100%' %>
    <div class="actions">
      <%= f.submit '发布微博',:class => 'btn btn-primary' %>
    </div>
<% end %>

app/views/weibos/_msg.html.erb
  <div style="clear:both;padding-bottom:10px;">
    
    <div style="float:left;padding-right:20px"><%= image_tag("rails.png") %></div>
    <div>
      <div><b>sb用户</b></div>
      <div  class="hero-unit" style="background:rgb(243, 243, 243);"> <%= msg.content%> </div>
      <div>
        <div style="float:right">
          <a class="btn btn-link" id="<%= "comment#{msg.id}" %>" name="<%= msg.id %>"><%= "(评论#{msg.comments.count})" %></a>
          <span> <%= msg.ctime.strftime('%Y-%m-%d %H:%M:%S').to_s %> </span>
        </div>
      </div>
    </div>
    <div style="clear:both;display:none;" id="<%= msg.id %>">
      <%= form_for([msg,msg.comments.build]) do |f| %>
         <div class="field">
           <%= f.text_area :body,:placeholder =>'评论',:size =>'40*4',:style =>'width:100%;' %>
         </div>
         <div class="action">
           <%= f.submit '提交',:class => "btn btn-info" %>
         </div>
      <% end %>
         <!--评论-->
      <% msg.comments.each do |comment| %>
        <div>
          <%= comment.body %>&nbsp;&nbsp;<%= comment.ctime %> 回复<br/>
          <%= form_for([msg,comment.comments.build]) do |f| %>
            <div class="field">
              <%= f.text_area :body,:placerholder => '回复',:size => '40*4',:style =>'width:100%;' %>
            </div>
            <div class="action">
              <%= f.submit '回复',:class => 'btn btn-info' %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <hr/>

<script>
//$('#comment').toggle(function(){$('#'+this.name).show();},function(){$('#'+this.name).hidden();});
//popover({placement:'bottom',content:function(){$('#'+this.name).show();}});
$('#'+"<%= "comment#{msg.id}" %>").click(function(){$('#'+this.name).toggle(500);});
//$('#'+"<%= "comment#{msg.id}" %>").click(function(){alert("who are you");});
</script>

app/views/weibos/_weibo.html.erb
<a>func</a>
<%= weibo.content %>

app/views/weibos/_weibo.json.erb
  <div style="clear:both;padding-bottom:10px;">
    
    <div style="float:left;padding-right:20px"><%= image_tag("rails.png") %></div>
    <div>
      <div><b>sb用户</b></div>
      <div  class="hero-unit" style="background:rgb(243, 243, 243);"> <%= weibo.content%> </div>
      <div>
        <div style="float:right">
          <a class="btn btn-link" id="<%= "comment#{weibo.id}" %>" name="<%= weibo.id %>"><%= "(评论#{weibo.comments.count})" %></a>
          <span> <%= weibo.ctime.strftime('%Y-%m-%d %H:%M:%S').to_s %> </span>
        </div>
      </div>
    </div>
    <div style="clear:both;display:none;" id="<%= weibo.id %>">
      <%= form_for([weibo,weibo.comments.build]) do |f| %>
         <div class="field">
           <%= f.text_area :body,:placeholder =>'评论',:size =>'40*4',:style =>'width:100%;' %>
         </div>
         <div class="action">
           <%= f.submit '提交',:class => "btn btn-info" %>
         </div>
      <% end %>
         <!--评论-->
      <% weibo.comments.each do |comment| %>
        <div>
          <%= comment.body %>&nbsp;&nbsp;<%= comment.ctime %> 回复<br/>
          <%= form_for([weibo,comment.comments.build]) do |f| %>
            <div class="field">
              <%= f.text_area :body,:placerholder => '回复',:size => '40*4',:style =>'width:100%;' %>
            </div>
            <div class="action">
              <%= f.submit '回复',:class => 'btn btn-info' %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <hr/>

<script>
//$('#comment').toggle(function(){$('#'+this.name).show();},function(){$('#'+this.name).hidden();});
//popover({placement:'bottom',content:function(){$('#'+this.name).show();}});
$('#'+"<%= "comment#{weibo.id}" %>").click(function(){$('#'+this.name).toggle(500);});
//$('#'+"<%= "comment#{weibo.id}" %>").click(function(){alert("who are you");});
</script>

app/views/weibos/edit.html.erb
<h1>Editing weibo</h1>

<%= render 'form' %>

<%= link_to 'Show', @weibo %> |
<%= link_to 'Back', weibos_path %>

app/views/weibos/index.html.erb
<!-- 微博窗口 -->
<%= render 'form' %>

<script>
$(function(){

  $("a[id^='comment']").tooltip({title:'评论'});
  $("a[id^='delete']").tooltip({title:'删除'});
  $('#msgbox').delegate("a[id^='comment']",'click',function(){$('#'+this.name).toggle(500);});
  $('#msgbox').delegate("a[id^='delete']","click",function(){
  var name = $(this).attr('name');
  $.ajax({
    url:'/weibos/'+$(this).attr('name'),
    type:'DELETE',
    dataType:'json',
    success:function(data){
      $('#msg'+name).fadeOut(1000,function(){
        $(this).remove();
      });
    },
    error:function(req,set){
      alert("error");
    }
  });
});

$('#new_weibo').on('submit',function(){
  $.ajax({
    url:$(this).prop('action'),
    //dataType:'script',
    data:$(this).serialize(),
    type:'POST',
    success:function(data){
      var tmp = data;
      $('#msgbox').prepend(tmp);
      $('#msgbox div:first').hide(0,function(){$(this).slideDown(1500);});
      $('#weibo_content').val('');
      $("a[id^='comment']").tooltip({title:'评论'});
      $("a[id^='delete']").tooltip({title:'删除'});
    },
    error:function(req,set){
      if(req.status == 200)
      {
        var tmp = $('#msgbox').html();
        tmp = req.responseText + tmp;
        $('#msgbox').html(tmp);
        $('#weibo_content').val('');
      }
      else{
        alert("error");
      }
    }
  });
  return false;
});
});
</script>

<div class="btn btn-link">
  <i class="icon-file"></i><a>微博</a>&nbsp;&nbsp;
  <i class="icon-eye-open"></i> <a>图片</a>&nbsp;&nbsp;
  <i class="icon-music"></i><a>Music</a>
</div>
<hr/>
<div id="msgbox">
  <%= render @weibos %>
</div>

<table class="table table-bordered table-hover" style="width:80%">
<% @weibos.each do |weibo| %>
  <tr>
    <td><%= weibo.content %></td>
    <td><%= weibo.ctime %></td>
    <td><%= weibo.wtype %></td>
    <td><%= weibo.flag %></td>
    <td><%= link_to 'Show', weibo %></td>
    <td><%= link_to 'Destroy', weibo, method: :delete, data: { confirm: 'Are you sure?',:remote => true } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/weibos/new.html.erb
<h1>New weibo</h1>

<%= render 'form' %>

<%= link_to 'Back', weibos_path %>

app/views/weibos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Userid:</b>
  <%= @weibo.userid %>
</p>

<p>
  <b>Content:</b>
  <%= @weibo.content %>
</p>

<p>
  <b>Ctime:</b>
  <%= @weibo.ctime %>
</p>

<p>
  <b>Type:</b>
  <%= @weibo.wtype %>
</p>

<p>
  <b>Flag:</b>
  <%= @weibo.flag %>
</p>


<%= link_to 'Edit', edit_weibo_path(@weibo) %> |
<%= link_to 'Back', weibos_path %>